name: Release Piper Action

on:
  workflow_dispatch:
  schedule:
#    - cron: '0 9 * * 1'  # at 9 am every Monday
    - cron: '*/10 * * * *'  # every 10 minutes

jobs:
  check_latest_commit_date:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v4
      - name: Print latest commit
        run: echo ${{ github.sha }}
      - id: should_run
        continue-on-error: true
        name: Check if latest commit is less than a week
        if: ${{ github.event_name == 'schedule' }}
#        run: test -z $(git rev-list  --after="7 days"  ${{ github.sha }}) &amp;&amp; echo "::set-output name=should_run::false"
        run: test -z $(git rev-list  --after="15 minutes"  ${{ github.sha }}) &amp;&amp; echo "::set-output name=should_run::false"

  release:
    name: Release with new tag
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get next version
        uses: reecetech/version-increment@2024.4.1
        id: version
        with:
          scheme: semver
          increment: minor
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          generate_release_notes: true
          make_latest: true

