name: Publish Piper Action

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 1'  # at 9 am every Monday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get next version
        uses: reecetech/version-increment@2024.4.1
        id: version
        with:
          scheme: semver
          increment: minor
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          generate_release_notes: true
          make_latest: true
          
